server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
    }

    location /assets {
        # Our assets are all explicitely versioned, so
        # serve them with a very long cache lifetime
        add_header Cache-Control "max-age=31536000";
    }
}

