name: ci

on:
  push:
    branches:
      - "master"
      - "test"

jobs:
  build:
    runs-on: actions-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -lah
      - run: ls -lah ./.github/build-action
      - name: build-action
        uses: ./.github/build-action

  deploy:
    runs-on: actions-runner
    needs: build
    environment:
      name: test
      url: https://webbi-test.wappuradio.fi
    steps:
      - name: build-action
        uses: ./.github/build-action
        with:
          kubeconfig: "${{ secrets.KUBECONFIG_BASE64 }}"
          image: "ghcr.io/wappuradio/webbi:${{ github.sha }}"
          env: "test"
